/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2021-05-10-f8d910e-QtAV"
#endif /* AVUTIL_FFVERSION_H */
